import type { Metadata } from "next";
import "./style/globals.css";

import Footer from "./components/common/footer";
import Header from "./components/common/header";
import { montserrat } from "./style/font";

export const metadata: Metadata = {
  title: "Metaboost Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
